"""agrega campos para colaboracion

Revision ID: 0e55874d88d6
Revises: b658c90d3c67
Create Date: 2025-01-14 00:03:25.154460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e55874d88d6'
down_revision: Union[str, None] = 'b658c90d3c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('shared_with', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('note', sa.Column('last_edited_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'user', ['last_edited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'last_edited_by')
    op.drop_column('note', 'shared_with')
    op.drop_column('note', 'version')
    # ### end Alembic commands ###
