"""actualiza a timestamp las columas de update y created

Revision ID: 7021c7347e45
Revises: 0e55874d88d6
Create Date: 2025-01-14 02:00:21.319736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7021c7347e45'
down_revision: Union[str, None] = '0e55874d88d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
